#!/usr/bin/env python3

import sys
import signal
import os
from BoilerPlate import MyApplication

if __name__ == "__main__":
    # Allow application shutdown with Ctrl-C in terminal
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    dir_path = os.path.dirname(os.path.realpath(__file__))
    os.chdir(dir_path)
    app = MyApplication()
    exit_status = app.run(sys.argv)
    sys.exit(exit_status)
